// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfttasxtzlmnfwstxxkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdHRhc3h0emxtbmZ3c3R4eGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTc0MDcsImV4cCI6MjA3MDkzMzQwN30.ydICN88BQBFpM-5BwkyraVYgKfsNauX962ghJ_C4eFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});