// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Migrated onto the shared babytoefu Supabase project. This app's tables live
// in the dedicated `portfolio` schema there (so they don't collide with
// babytoefu's own tables); storage uses the `project-files` bucket as before.
const SUPABASE_URL = "https://knoctjndbbnqjaamfsyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_upVuPujQNukocjT4ZN3cRw_aoPpYxrr";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'portfolio',
  },
});